feat: Session/4
Kotaro666-dev/flutter-training-202312 pull request #19
Opened 2023-12-05 10:01 UTC by Kotaro666-dev

## 課題

close #5 

## 対応箇所

- [x] レイアウトが表示された後に「何かしらの処理」を行うMixin を作成する
- [x] 作成した Mixin の使用先で「何かしらの処理」を記述できるようにする
- [x] Session3 で作成した以下の処理を作成した Mixin を使って書き直す

## 動作

| mixin 移行前 | mixin 移行後 |
|----------|--------|
| <video src="https://github.com/Kotaro666-dev/flutter-training-202312/assets/54063249/f446c89c-a36f-4cbf-9b18-d2989328f47a" /> | <video src="https://github.com/Kotaro666-dev/flutter-training-202312/assets/54063249/467a4224-e945-4e58-9655-c9571470bca0" /> |

2023-12-06 04:50 UTC, Kotaro666-dev commented on lib/core/components/weather_page_navigation_mixin.dart
> +mixin WeatherPageNavigationMixin<T extends StatefulWidget> on State<T> {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

以下の実装を参考にしています。

```dart
mixin AutomaticKeepAliveClientMixin<T extends StatefulWidget> on State<T> {
  KeepAliveHandle? _keepAliveHandle;
  ... 省略
}
```

2023-12-06 04:51 UTC, Kotaro666-dev commented on lib/core/components/weather_page_navigation_mixin.dart
> +  Future<void> _goToWeatherPageAfterFrameCompletes() async {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

処理内容は `SplashPage` 内に定義しているものをそのまま持ってきています。

2023-12-07 03:07 UTC, Yamasaki-pan961 requested changes

2023-12-07 03:07 UTC, Yamasaki-pan961 commented on lib/core/components/weather_page_navigation_mixin.dart
> +mixin WeatherPageNavigationMixin<T extends StatefulWidget> on State<T> {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
> - レイアウトが表示された後に「何かしらの処理」を行うMixin を作成する
> - 作成した Mixin の使用先で「何かしらの処理」を記述できるようにする

 レイアウトが表示された後に任意の処理を行うMixin を作成し、
そのMixinをSplashページで使い、遷移の処理を記述できるようにすることが、今回の課題となっております。

2023-12-07 03:12 UTC, Kotaro666-dev commented on lib/core/components/weather_page_navigation_mixin.dart
> +mixin WeatherPageNavigationMixin<T extends StatefulWidget> on State<T> {
# 仕様について擦り合わせをして理解したこと

- レイアウトの描画が完了することを待ち、「何かしらの処理」を実行する Mixin を作成する（`CustomAfterLayoutMixin`）
- 作成した Mixin の使用先（今回の場合だと、スプラッシュ画面）側で「何かしらの処理」を記述できるようにする
- Session3 で作成した処理（新しい画面が表示されたら、0.5 秒後に前回まで作っていた画面に遷移する）のうち、新しい画面が表示されたらの部分を mixin で実行されて、残りの処理がスプラッシュ画面内の実装で続いて発生する

2023-12-07 03:48 UTC, Kotaro666-dev commented on lib/core/components/weather_page_navigation_mixin.dart
> +mixin WeatherPageNavigationMixin<T extends StatefulWidget> on State<T> {
以下のコミットで対応しました。

- https://github.com/Kotaro666-dev/flutter-training-202312/pull/19/commits/ad95404d918c8177bdc3668498ed59ea4ccf8fa9
- https://github.com/Kotaro666-dev/flutter-training-202312/pull/19/commits/f8da901b934caede491c1db72fc1b3d73ba1303e

2023-12-11 02:30 UTC, Yamasaki-pan961 commented on lib/core/components/after_layout_mixin.dart
> +  Future<void> doActioinAfterFrameCompletes() async {
![nits-badge](https://img.shields.io/badge/review-nits-pink.svg)
タイポです。
```suggestion
  Future<void> doActionAfterFrameCompletes() async {
```

2023-12-11 02:31 UTC, Yamasaki-pan961 approved these changes

2023-12-11 03:11 UTC, Kotaro666-dev commented
レビューありがとうございます。
マージします！

2023-12-11 03:11 UTC, merged

2023-12-22 00:17 UTC, Kotaro666-dev commented on lib/core/components/after_layout_mixin.dart
> +  Future<void> doActioinAfterFrameCompletes() async {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

VSCode拡張パッケージの Code Spell Checker では、フォルダ全体でスペルチェックする機能がないようです。

その代わり、Code Spell Checker の基になってりう cspell コマンドラインツールを使うことで、フォルダ全体のスペルチェックを行うことができるようになるようです。

## 参考資料

- [How to run VSCode Code Spell Checker extension on an entire folder?/](https://stackoverflow.com/questions/59569202/how-to-run-vscode-code-spell-checker-extension-on-an-entire-folder)
- GitHub Issue - Option to run spell check on entire files/folders [#376](https://github.com/streetsidesoftware/vscode-spell-checker/issues/376)
- [cspell-npm](https://www.npmjs.com/package/cspell)