[Draft] feat: Session/9
Kotaro666-dev/flutter-training-202312 pull request #24
Opened 2023-12-14 08:33 UTC by Kotaro666-dev

## 課題

close #10

## 対応箇所

- [x] [yumemi_weather] API の呼び出しから Widget へ通知する部分までの [Unit tests] を書く
- [x] 余力があれば、JSON のエンコード・デコードの [Unit tests] も書く

## 動作

```bash
flutter-training-202312 git:(session/9) ✗ fvm flutter test                                                   
00:00 +0: loading /Users/k_kamashima/flutter-training-202312/test/data/repository/weather_repository_impl_test.dart                                                                                 00:01 +0: loading /Users/k_kamashima/flutter-training-202312/test/data/repository/weather_repository_impl_test.dart                                                                                 00:01 +0: /Users/k_kamashima/flutter-training-202312/test/data/repository/weather_repository_impl_test.dart: WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が正常なレスポン00:01 +1: /Users/k_kamashima/flutter-training-202312/test/data/repository/weather_repository_impl_test.dart: WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が正常なレスポン00:01 +1: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が不正なパラメータ例外を投げる場合_アプリ内独自の不正なパラメータ例外を投げる                                  00:01 +2: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が不正なパラメータ例外を投げる場合_アプリ内独自の不正なパラメータ例外を投げる                                  00:01 +2: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が不明な天気情報例外を投げる場合_アプリ内独自の不明な天気情報例外を投げる                                      00:01 +3: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が不明な天気情報例外を投げる場合_アプリ内独自の不明な天気情報例外を投げる                                      00:01 +3: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が天気状態フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +4: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が天気状態フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +4: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が最高気温フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +5: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が最高気温フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +5: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が最低気温フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +6: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が最低気温フィールドを欠損したレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外を00:01 +6: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が定義されていない天気状況を含むレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外00:01 +7: ... WeatherRepositoryImpl#fetchWeather(天気情報を取得する) 天気情報取得処理が定義されていない天気状況を含むレスポンスを返却する場合_ドメインクラスへのデコードに失敗し、不明な天気情報例外00:01 +7: loading /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart                                                                                             00:01 +7: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson 正常なJSONデータをWeatherResponseにデコードする場合_正常なWeatherResponse00:01 +8: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson 正常なJSONデータをWeatherResponseにデコードする場合_正常なWeatherResponse00:01 +8: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson 空のJSONデータをWeatherResponseにデコードする場合_フィールドが空のWeatherR00:01 +9: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson 空のJSONデータをWeatherResponseにデコードする場合_フィールドが空のWeatherR00:01 +9: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson weather_condition フィールドに文字列型ではない値を含むJSONデータをWeatherR00:01 +10: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson weather_condition フィールドに文字列型ではない値を含むJSONデータをWeather00:01 +10: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson max_temperature フィールドに整数ではない値を含むJSONデータをWeatherRespon00:01 +11: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson max_temperature フィールドに整数ではない値を含むJSONデータをWeatherRespon00:01 +11: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson min_temperature フィールドに整数ではない値を含むJSONデータをWeatherRespon00:01 +12: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson min_temperature フィールドに整数ではない値を含むJSONデータをWeatherRespon00:01 +12: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson date フィールドに文字列ではない値を含むJSONデータをWeatherResponseにデコ00:01 +13: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson date フィールドに文字列ではない値を含むJSONデータをWeatherResponseにデコ00:01 +13: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson temperature フィールドに文字列型の整数値を含むJSONデータをWeatherResponse00:01 +14: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_response_test.dart: WeatherResponse#fromJson temperature フィールドに文字列型の整数値を含むJSONデータをWeatherResponse00:01 +14: loading /Users/k_kamashima/flutter-training-202312/test/data/model/weather_request_test.dart                                                                                             00:01 +14: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_request_test.dart: WeatherRequest#toJson 正常なWeatherRequestをJSONにエンコードする場合_正常なJSONを返却する          00:01 +15: /Users/k_kamashima/flutter-training-202312/test/data/model/weather_request_test.dart: WeatherRequest#toJson 正常なWeatherRequestをJSONにエンコードする場合_正常なJSONを返却する          00:01 +15: loading /Users/k_kamashima/flutter-training-202312/test/data/remote/weather_remote_data_source_impl_test.dart                                                                            00:01 +15: ... WeatherRemoteDataSourceImpl#fetchWeather(天気情報を取得する) YumemiWeatherが正常なレスポンスを返却する場合_正常なレスポンスを返却する                                                00:01 +16: ... WeatherRemoteDataSourceImpl#fetchWeather(天気情報を取得する) YumemiWeatherが正常なレスポンスを返却する場合_正常なレスポンスを返却する                                                00:01 +16: loading /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart                                                                                            00:01 +16: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に成功した場合_成功結果を返却する      00:01 +17: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に成功した場合_成功結果を返却する      00:01 +18: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に成功した場合_成功結果を返却する      00:01 +19: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に成功した場合_成功結果を返却する      00:01 +19: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に失敗した場合_失敗結果を返却する      00:01 +20: /Users/k_kamashima/flutter-training-202312/test/domain/get_weather_use_case_test.dart: GetWeatherUseCase#call(天気情報を取得する) 天気情報取得処理に失敗した場合_失敗結果を返却する      00:01 +20: loading /Users/k_kamashima/flutter-training-202312/test/presentation/weather/weather_page_state_provider_test.dart                                                                       00:01 +20: /Users/k_kamashima/flutter-training-202312/test/presentation/weather/weather_page_state_provider_test.dart: WeatherPageState(天気画面の状態) 天気画面の状態が生成された場合_天気画面の状00:01 +21: /Users/k_kamashima/flutter-training-202312/test/presentation/weather/weather_page_state_provider_test.dart: WeatherPageState(天気画面の状態) 天気画面の状態が生成された場合_天気画面の状00:01 +21: /Users/k_kamashima/flutter [...]

2023-12-14 09:11 UTC, Kotaro666-dev commented on test/presentation/weather/weather_page_state_provider_test.dart
> +            container.listen(weatherPageStateProvider, (_, __) {});
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

[公式ドキュメント](https://riverpod.dev/ja/docs/essentials/testing)で以下のように記載されているため、listen するような書き方にしました。

> Be careful when using container.read when providers are automatically disposed.
If your provider is not listened to, chances are that its state will get destroyed in the middle of your test.
In that case, consider using container.listen.
Its return value enables reading the current value of provider anyway, but will also ensure that the provider is not disposed in the middle of your test:

`container.read`でも動くことは動きます。

2023-12-14 09:13 UTC, Kotaro666-dev commented on test/data/remote/weather_remote_data_source_impl_test.dart
> +  }
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

[公式ドキュメント](https://riverpod.dev/ja/docs/essentials/testing)に記載されている方式で `ProviderContainer` のインスタンスを生成するメソッドを用意しています。

> It is encouraged to make a testing utility for both creating and disposing of a ProviderContainer object:


```dart
  test('Some description', () {
    // Create a ProviderContainer for this test.
    // DO NOT share ProviderContainers between tests.
    final container = createContainer();
```

2023-12-14 09:16 UTC, Kotaro666-dev commented on test/data/remote/weather_remote_data_source_impl_test.dart
> +import 'weather_remote_data_source_impl_test.mocks.dart';
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

[Flutter の mockito を使用したドキュメント](https://docs.flutter.dev/cookbook/testing/unit/mocking#3-create-a-test-file-with-a-mock-httpclient)では `@GenerateMocks` を使った例が載っていますが、mockito のドキュメントには以下のように記載されています。

> Mockito provides two APIs for generating mocks, the @GenerateNiceMocks annotation and the @GenerateMocks annotation. The recommended API is @GenerateNiceMocks. The difference between these two APIs is in the behavior of a generated mock class when a method is called and no stub could be found.

2023-12-14 09:23 UTC, Kotaro666-dev commented on test/data/model/weather_response_test.dart
> +      );
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

メソッドの呼び出しで例外が発生するものは、`expect` メソッド内で実行すれば try..catch...構文にせずとも例外判定することができるようです。
そのため、例外確認テストケースはこうした書き方にしています。
正常な結果が返却されるものは基本的に `expected` 変数に格納するようにしてリーディングしやすいようにしています。

2023-12-19 11:45 UTC, Yamasaki-pan961 requested changes
1点指摘しています

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on pubspec.yaml
> +  test: ^1.24.9
![nits-badge](https://img.shields.io/badge/review-nits-pink.svg)
Flutterプロジェクトのデフォルトで導入されている `flutter_test` パッケージの中に含まれるので、不要になります。

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on test/data/model/weather_request_test.dart
> +  group('WeatherRequest#toJson', () {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
このテストグループの書き方はAndroid開発だと主流なのでしょうか？
Flutterでは書き方が特に決まってないのでAndroidではどうなのか知りたいです。

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on test/data/model/weather_response_test.dart
> +      );
参考になります!

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on test/data/remote/weather_remote_data_source_impl_test.dart
> +            ),
![must-badge](https://img.shields.io/badge/review-must-red.svg)
テストの事後条件と実装の乖離がありそうです。
```suggestion
            throwsA(
              YumemiWeatherError.unknown,
            ),
```

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on test/data/remote/weather_remote_data_source_impl_test.dart
> +              isA<YumemiWeatherError>(),
![must-badge](https://img.shields.io/badge/review-must-red.svg)
こちらもテストの事後条件と実装の乖離がありそうです。
```suggestion
              YumemiWeatherError.invalidParameter,
```

2023-12-19 11:45 UTC, Yamasaki-pan961 commented on test/domain/get_weather_use_case_test.dart
> +      expect((actual as Success<Weather>).data, expected);
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
`sealed`クラスを継承したクラスでは等価性がなくなるのですね、、、
以下のように書くにはFreezedクラスにする必要ですね
```dart
expect(actual, const Success<Weather>(data: expected));
```

2023-12-19 23:19 UTC, Kotaro666-dev commented on pubspec.yaml
> +  test: ^1.24.9
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

[ユニットテストに関係する公式ドキュメント](https://docs.flutter.dev/cookbook/testing/unit/introduction)にも以下のように書いてあることを確認しました。

> Unit tests are handy for verifying the behavior of a single function, method, or class. The [test](https://pub.dev/packages/test) package provides the core framework for writing unit tests, and the [flutter_test](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html) package provides additional utilities for testing widgets.

2023-12-19 23:24 UTC, Kotaro666-dev commented on pubspec.yaml
> +  test: ^1.24.9
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

公式ドキュメントの初期段階の記述では、以下のような記述がされていることを確認しました。

- `test` パッケージ: Flutter に依存していない Dart パッケージでの開発する場合
- `flutter_test` パッケージ: Flutter アプリでのみ使用される、またはWidgetテストを記述する場合

https://github.com/flutter/website/commit/a5b183d4ec389cecada3c7830c9fb6c6e40615f3#diff-c36283b09b494d087e72e5a286d4625523e25fa8d6acce82ba6646948b1a6094R28-R49

2023-12-19 23:26 UTC, Kotaro666-dev commented on pubspec.yaml
> +  test: ^1.24.9
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

`flutter_test` パッケージは、 `test` パッケージを基にしてWidgetテストに必要な機能やその他便利な機能が追加されたパッケージという理解をしました。

> Testing library for flutter, built on top of package:test.

https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html

2023-12-19 23:31 UTC, Kotaro666-dev commented on pubspec.yaml
> +  test: ^1.24.9
以下のコミットにて、`test` パッケージを削除する対応をしました。

- https://github.com/Kotaro666-dev/flutter-training-202312/pull/24/commits/3d721fb8f6a9a821cba188e7e58be66efa946d95
- https://github.com/Kotaro666-dev/flutter-training-202312/pull/24/commits/34d83f2a36bc1a54db4c001317b9d30b718f4ac1

2023-12-19 23:42 UTC, Kotaro666-dev commented on test/data/model/weather_request_test.dart
> +  group('WeatherRequest#toJson', () {
質問ありがとうございます。

> このテストグループの書き方はAndroid開発だと主流なのでしょうか？

Android 開発では今回の Flutter テストコードのようにテスト項目を `group` でまとめる対応をした記憶はなく、またそのような書き方はなさそうです。

Android 開発ではテストコードをクラス内に記述するようになっており、このクラスでの命名が Flutter でのテストグループと同じ意味を持つようになるのかなと思いました。

```kotlin
class EmailValidatorTest {
  @Test fun emailValidator_CorrectEmailSimple_ReturnsTrue() {
    assertTrue(EmailValidator.isValidEmail("name@email.com"))
  }

}
```

2023-12-19 23:44 UTC, Kotaro666-dev commented on test/data/model/weather_request_test.dart
> +  group('WeatherRequest#toJson', () {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

今回のグループ名に関しては、以下のテストコード規約に記載されたルールを参考にして命名しています。

https://product.10x.co.jp/entry/test-coding-standards-in-10X-202303#group%E3%81%AB%E3%81%AF%E3%83%86%E3%82%B9%E3%83%88%E5%AF%BE%E8%B1%A1%E3%82%92%E6%9B%B8%E3%81%8F

2023-12-20 00:07 UTC, Kotaro666-dev commented
@Yamasaki-pan961 

指摘箇所の修正および質問に回答しました。
お手隙で再度レビューをお願いします。

2023-12-20 04:35 UTC, Yamasaki-pan961 approved these changes
LGTMです！！

2023-12-20 04:35 UTC, Yamasaki-pan961 commented on test/domain/get_weather_use_case_test.dart
> +      expect((actual as Success<Weather>).data, expected);
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

==オペレータをoverrideする際は正しく書く必要があるようです。
https://dart.dev/tools/linter-rules/hash_and_equals

2023-12-20 04:48 UTC, Kotaro666-dev commented
レビューありがとうございます！
マージします！

2023-12-20 04:48 UTC, merged